apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  namespace: census-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:3.9
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
          ports:
            - containerPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: census-processing
spec:
  ports:
    - port: 2181
  selector:
    app: zookeeper
